# Site settings
title: Landline Docs
email: chuck@assembly.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation and guides for Landline.io
baseurl: ""
url: "http://docs.landline.io"

# Build settings
markdown: redcarpet
