# Site settings
title: Landline Docs
email: chuck@assembly.com
description: > # this means to ignore newlines until "baseurl:"
  All the documentation for getting set up with Landline.io
baseurl: "/landline-docs/"
url: "http://docs.landline.io"

# Build settings
markdown: redcarpet
